#!/venv/bin/python

from tests.data_preporation.test_custom_transformer import TestCustomTransformer  # noqa
from tests.models.test_train import TestModelTraining                             # noqa
from tests.models.test_predict import TestModelPrediction                         # noqa
from tests.models.test_evaluate import TestModelEvaluation                        # noqa
from tests.pipeline_tests.test_pipeline import TestPipeline                       # noqa


import unittest


def run_tests():
    unittest.main()


if __name__ == "__main__":
    run_tests()
