name: HW1 CI

on:
  push:
    branches: [ "hw1" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
        
    - name: Install project
      run: |
        cd ml_project
        pip install -e .
        
    - name: Test programm
      run: |
        cd ml_project
        run_tests